---
title: "Slope Chart in R"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

## The Slope Chart
By now we discussed the slope chart multiple times in lecutres. 
This includes

* appropriate times to use the chart,
* multiple ways to make the chart,
* fine tuning aspects of the chart. 

So there is really not a reason to repeat those aspects of explanation here.
You also saw two different approaches to crafting the chart in Microsoft Excel. 
Recall the basics of those two approaches are the same, one gave us an easier time to create labels if that was the way we wanted to go. 
We are going to have one twist here and it comes with the data and is a really important distinction you need to know if you plan to use data in your career. 

## Data Discussions
We use the same types of commands as we did last time to load the libraries and the data for us. 

```{r Package set up and data location}
library(tidyverse)
urlfile="https://raw.githubusercontent.com/flynnecon/datavizf25/refs/heads/main/data/birth_rates_370f25.csv"
```




This data is in a format called *wide*.
Think of it like this, every variable is in a column of its own.
This is one way to store data and it is perfectly fine and works for the mindset of most people.
However, there are alternative ways to organize data and we are going to explore one of them here, called *longer* data. 
This works when variables themselves might simply be a value we can use in identification. 
Think, for example, of **male** versus **female** test scores. 
We could have a variable for each, and there are situations where that makes sense, or we could use the sex identifier as a value in another variable, in this case *sex*. 


